### ISSUE TITLE
pod: command not found

### ISSUE THREAD

**Issue by exos** [q6112345/react-native-google-place-picker#14]
```
▶ LC_ALL=C react-native link
Preparing to link react-native-google-place-picker for iOS
Checking CocoaPods...
CocoaPods already installed
rnpm-install info Android module react-native-google-place-picker is already linked
rnpm-install info iOS module react-native-google-place-picker is already linked
Checking Podfile in iOS project (/home/exos/alpha/*****/com.*****.app/ios/Podfile)

Found an existing Podfile, Do you want to override it? [N/y]
y
Adding Podfile to iOS project
Installing Pods
node_modules/react-native-google-place-picker/bin/cocoapods.sh: line 45: pod: command not found
/home/exos/alpha/*****/com.*****.app/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${ command }" command`);
        ^

Error: Error occured during executing "node_modules/react-native-google-place-picker/bin/cocoapods.sh" command
    at ChildProcess.prelink (/home/exos/alpha/*****/com.*****.app/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by exos** [comment]
I resolved it installing cocoapods
